- hosts: localhost
  gather_facts: false
  roles:
    - role: emulate_flagger
      vars:
        app_name: my-app
        namespace: default
        strategy: bluegreen  # or 'canary'
        new_image: myrepo/my-app:{{ CI_COMMIT_SHA }}
